services:
  redis1:
    image: redis:latest
    container_name: redis1
    command: ["redis-server","--appendonly", "yes" ,"--cluster-enabled", "yes", "--cluster-announce-ip","${ANNOUNCE_IP}","--cluster-announce-port","7001","--cluster-announce-bus-port","17001"]
    ports:
      - 7001:6379
      - 17001:16379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis2:
    image: redis:latest
    container_name: redis2
    command: ["redis-server","--appendonly", "yes" ,"--cluster-enabled", "yes", "--cluster-announce-ip","${ANNOUNCE_IP}","--cluster-announce-port","7002","--cluster-announce-bus-port","17002"]
    ports:
      - 7002:6379
      - 17002:16379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis3:
    image: redis:latest
    container_name: redis3
    command: ["redis-server","--appendonly", "yes" ,"--cluster-enabled", "yes", "--cluster-announce-ip","${ANNOUNCE_IP}","--cluster-announce-port","7003","--cluster-announce-bus-port","17003"]
    ports:
      - 7003:6379
      - 17003:16379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis4:
    image: redis:latest
    container_name: redis4
    command: ["redis-server","--appendonly", "yes" ,"--cluster-enabled", "yes", "--cluster-announce-ip","${ANNOUNCE_IP}","--cluster-announce-port","7004","--cluster-announce-bus-port","17004"]
    ports:
      - 7004:6379
      - 17004:16379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis5:
    image: redis:latest
    container_name: redis5
    command: ["redis-server","--appendonly", "yes" ,"--cluster-enabled", "yes", "--cluster-announce-ip","${ANNOUNCE_IP}","--cluster-announce-port","7005","--cluster-announce-bus-port","17005"]
    ports:
      - 7005:6379
      - 17005:16379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis6:
    image: redis:latest
    container_name: redis6
    command: ["redis-server","--appendonly", "yes" ,"--cluster-enabled", "yes", "--cluster-announce-ip","${ANNOUNCE_IP}","--cluster-announce-port","7006","--cluster-announce-bus-port","17006"]
    ports:
      - 7006:6379
      - 17006:16379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
